kind: project
metadata:
  name: gate-alfa
  created: '2023-12-19T13:37:37.304581'
  labels:
    temp: 'True'
spec:
  description: The test project, part of quality gate
  functions: []
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/george0st/qgate-sln-mlrun.git#refs/heads/transaction
  origin_url: git://github.com/george0st/qgate-sln-mlrun.git#refs/heads/transaction
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
